### ISSUE TITLE
Concept of server sets with different connection strategies

### ISSUE THREAD

**Issue by jlzhao27** [palantir/conjure-java-runtime#114]
As MP was investigating a failover LDAP client, we found the library we were using had a pretty cool way of doing failover.

Basically, the client takes a `ServerSet` and the `ServerSet` is responsible for deciding which URL to pick. The basic `FailoverServerSet` would be identical to the current `FailoverFeignTarget` but adding a level of indirection allows you to compose different `ServerSet`s. For example, we can define a `RoundRobinServerSet` which always RR each request regardless of failover and the `FailoverServerSet` can take a list of `RoundRobinServerSet`s. This enables support for complex network topologies such as east/west coast data centers.

Basic proposal, add object `ServerSet` and allow application to specify `serviceUrls` in terms of `ServerSet`s, example:

```
serviceUrls:
  type: failover
  serverSets: 
    - type: roundrobin
      serverSets:
      - east1                      # defaults to SingleServerSet type
      - east2
    - type: roundrobin
      serverSets:
      - west1
      - west2
```

Thoughts?
