### ISSUE TITLE
Incorrect assertion failure for null values.

### ISSUE THREAD

**Issue by laflechejonathan** [palantir/conjure-java-runtime#999]
With an object that looks like:

```yaml
      Foo:
          someField:
            type: optional<set<Bar>>
```

If I write a test:
```
ObjectMappers.newClientObjectMapper().convertValue(Foobar.builder().build(), Map.class);
```

I will hit an assertion failure: `Null values are not allowed by Conjure`. I believe this was introduced in https://github.com/palantir/conjure-java-runtime/pull/979, and doesn't seem like the desired behavior here.
